export const palabras = [
  'Cactus', 'Igloo', 'Marsopa', 'Pingüino', 'Auriculares', 'Tigre', 'Monóculo', 'Pluma', 'Libro', 'Crayón', 'Trineo', 'Caballitos de mar', 'Trofeo', 'Puma', 'Zorro', 'Billetera', 'Pavo real', 'Rubí', 'Cerdo', 'Almohada', 'Submarino', 'Iceberg', 'Rascacielos', 'Sombrero', 'Hidrante', 'Lápiz', 'Granja', 'Sello', 'Ornitorrinco', 'Regla', 'Hamaca', 'Caja', 'Pastel', 'Arpa', 'Dinosaurio', 'Guitarra', 'Llave inglesa', 'Ancla', 'Escalera', 'Calavera', 'Silbato', 'Violín', 'Radio', 'Chocolate', 'Mapa', 'Flor', 'Televisión', 'Diccionario', 'Mármol', 'Sombrilla', 'Oruga', 'Chile', 'Sacacorchos', 'Pizarra', 'Horno', 'Pluma de escribir', 'Metrónomo', 'Queso', 'Varita mágica', 'Pato', 'Parrilla', 'Estufa', 'Huevo', 'Correa', 'Termo', 'Espejo', 'Cámara', 'Tenedor', 'Cerilla', 'Reloj', 'Espejo', 'Ratón', 'Corona', 'Globo', 'Ballena', 'Grapadora', 'Martillo', 'Casco', 'Sierra', 'Cereza', 'Tienda de campaña', 'Cuchillo', 'Pizza', 'Estrella de mar', 'Cadena', 'Miel', 'Tienda', 'Toalla', 'Maní', 'Pizza', 'Revista', 'Sol', 'Luna', 'Nube', 'Escoba', 'Estrella de mar', 'Cucharón', 'Estatua', 'Gato', 'Lavabo', 'Salchicha', 'Ciervo', 'Piña', 'Gusano', 'Ratón', 'Coco', 'Unicornio', 'Brújula', 'Sandalia', 'Cuervo', 'Batería', 'Pantufla', 'Baloncesto', 'Bola de nieve', 'Cuerda', 'Coche', 'Mandil', 'Snorkel', 'Camisa', 'Subibaja', 'Dragón', 'Martillo neumático', 'Cremallera', 'Arena', 'Calamar', 'Computadora', 'Tambor', 'Maleta', 'Manta', 'Girasol', 'Sándwich', 'Bota', 'Techo', 'Collar', 'Camión', 'Molino de viento', 'Lámpara', 'Escarabajo', 'Fideos ramen', 'Catapulta', 'Sandía', 'Linterna', 'Delfín', 'Cama', 'Anillo', 'Inodoro', 'Globo terráqueo', 'Puerta', 'Calcetín', 'Pan', 'Gong', 'Palillos', 'Horca', 'Silla de ruedas', 'Medusa', 'Capa', 'Mosquito', 'Café', 'Bicicleta', 'Ducha', 'Puente', 'Avestruz', 'Panda', 'Recibo', 'Tobogán', 'Esqueleto', 'Castillo', 'Espátula', 'Jirafa', 'Satélite', 'Espada', 'Mariposa', 'Fósil', 'Pañuelo', 'Micrófono', 'Almuerzo', 'Caja de almuerzo', 'Corazón', 'Ladrillo', 'Escudo', 'Diamante', 'Peine', 'Tortuga', 'Ladrillo', 'Portal', 'Cerebro', 'Chimenea', 'Cortacésped', 'Portátil', 'Silla', 'Puerta', 'Oso', 'Caja fuerte', 'Planeta', 'Tren', 'Periódico', 'Rodillo de vapor', 'Ascensor', 'Pirámide', 'Trineo', 'Pulpo', 'Arco iris', 'Escalera', 'Paloma', 'Barco', 'Jabón', 'Telescopio', 'Ventana', 'Botella', 'Muñeca', 'Casa', 'Grúa', 'Burrito', 'Caracol', 'Patineta', 'Helicóptero', 'Calabaza', 'Árbol', 'Hormiga', 'Cepillo de dientes', 'Misil', 'Perico', 'Esponja', 'Aguja', 'Canasta', 'Máscara', 'Tiza', 'Leche', 'Aspiradora', 'Flotador', 'Cesta', 'Col', 'Pastel', 'Órgano', 'Palanca', 'Robot', 'Cometa', 'Bandera', 'Casa de pájaros', 'Microondas', 'Podio', 'Vino', 'Manzana', 'Té', 'Rosa', 'Mantequilla', 'Destornillador', 'Camello', 'Vacío', 'Pluma', 'Borrador', 'Pala', 'Tijeras', 'Cepillo de dientes', 'Cuchillo', 'Joya', 'Jarra', 'Anillo', 'Llave', 'Águila', 'Paracaídas', 'Diamante', 'Tiara', 'Tronco', 'Binoculares', 'Esquí', 'Caja', 'Correo', 'Sobre', 'Perro', 'Tostador', 'Montaña', 'Viento', 'Cinta adhesiva', 'Ambulancia'
];

export const pistas = [
  '¿Dónde lo encontrarías?',
  '¿Quién lo hace?',
  '¿Qué causa que la gente pelee por ello?',
  '¿En qué continente o región lo encontrarías más?',
  '¿En qué cuento de hadas o canción de cuna pertenece más?',
  '¿Con qué superhéroe se asocia más?',
  '¿Qué materia en la escuela enseña sobre esto?',
  '¿Qué forma geométrica tiene más?',
  '¿Dónde se almacena?',
  '¿Dónde lo comprarías u obtendrías?',
  '¿Con qué grupo de edad se asocia más?',
  '¿Con qué ciudad se asocia más?',
  '¿Qué es algo que usarías cuando lo llevas puesto?',
  '¿Qué palabra se te viene a la mente al escucharlo?',
  '¿Quién lo odia?',
  '¿Dónde está el más cercano?',
  '¿Cómo te sientes después de usarlo?',
  '¿Cómo te sientes cuando alguien te lo regala?',
  '¿Cuánto tiempo duraría si lo dejas solo?',
  '¿Qué lo cambia?',
  '¿Qué harías si solo tienes la mitad de él?',
  '¿En qué hábitat es más probable encontrarlo?',
  '¿Qué le pasa cuando lo dejas en la lluvia?',
  '¿Qué tipo de ruido hace?',
  '¿En qué punto de tu vida es más útil?',
  '¿Cómo te sientes acerca de él?',
  '¿Cómo afecta a las cosas a su alrededor?',
  '¿Cómo reaccionaría si lo empujaras cuesta abajo?',
  '¿Con qué país se asocia más?',
  '¿Qué se siente al tocarlo?',
  '¿Qué le pasa si lo pones bajo el agua?',
  '¿Con qué festividad se asocia más?',
  '¿Qué ruido hace cuando lo dejas caer?',
  '¿Qué superpoder desearía?',
  '¿Qué pasaría si lo enterraras por un año?',
  '¿En qué juego aparecería?',
  '¿Cuál es su opuesto?',
  '¿Quién en esta mesa lo usa más?',
  '¿Con qué frecuencia lo usas?',
  '¿Qué problema resuelve?',
  '¿Qué material no está hecho de esto?',
  '¿Con qué tipo de fiesta encajaría mejor?',
  '¿A qué hora del día se usa?',
  '¿Qué usarías para destruirlo?',
  '¿Cuál es una forma incorrecta de usarlo?',
  '¿De qué material secundario está hecho?',
  '¿Quién o qué puede levantarlo?',
  '¿Cómo se mueve?',
  '¿De qué tamaño es aproximadamente?',
  '¿Qué es igual de peligroso?',
  'Si fuera un instrumento musical, ¿cuál sería?',
  'Si tuviera una comida favorita, ¿cuál sería?',
  '¿Quién es una figura histórica que lo tenía o lo usaba?',
  '¿Quién es un personaje de ficción que lo tiene o lo usa?',
  '¿Cómo se transporta?',
  '¿Con qué concepto abstracto se asocia?',
  '¿Qué cuesta más o menos lo mismo?',
  '¿Qué pesa más o menos lo mismo?',
  'Si fuera un animal, ¿qué animal sería?',
  'Si fuera comida, ¿qué comida sería?',
  '¿Qué campo académico lo estudia?',
  '¿Quién es una celebridad que lo tiene o lo usa?',
  '¿Cómo se fabrica?',
  '¿Cómo lo usarías como arma?',
  '¿Qué adjetivo lo describe mejor?',
  '¿A qué categoría de objetos pertenece?',
  '¿En qué tipo de contenedor lo guardarías?',
  '¿A qué huele?',
  '¿Qué campo de la ciencia lo estudia?',
  '¿Para qué se usa?',
  '¿Qué tipo de personas lo utilizan?',
  '¿De qué material está hecho?',
  '¿Qué accidente o lesión causaría si lo usaras?',
  '¿Qué dios griego o romano antiguo se asocia más con él?',
  '¿De qué color es?',
  '¿Qué es algo que necesitas para usarlo?',
  '¿A qué sabe?',
  '¿Qué género de película o libro lo incluiría?',
  '¿Qué te hace usarlo?',
  '¿En qué tipo de tienda es más probable encontrarlo?',
  '¿Qué efecto sonoro (onomatopeya) hace (ej. "boom", "meow", etc.)?',
  '¿Qué lo alimenta?',
  '¿Qué es un libro, película o programa de TV donde aparece?',
  '¿Qué variedad de tipos tiene?',
  '¿Qué hay dentro de él?',
  '¿Qué es algo que puedes hacer usando esto?',
  '¿Dónde se usa?',
  '¿En qué parte de la casa lo encontrarías?',
  '¿Cuál es su apodo?',
  '¿Qué parte del cuerpo lo usarías con él?',
  '¿Con qué profesión trabaja?',
  '¿Cuál es una marca común de esto?',
  '¿Qué es algo que NO tiene nada que ver con él, solo para confundir al otro equipo?',
  '¿Qué es algo similar a él?',
  '¿Cuál es tu versión favorita de esto?',
  '¿A dónde va cuando se rompe?',
  'Si fuera un género musical, ¿qué género sería?',
  '¿Dónde se crea?',
  'Si fuera un juguete, ¿qué tipo de juguete sería?',
  'Si fuera un alimento de desayuno, ¿qué sería?',
  '¿Cómo se llama una versión jumbo de esto?',
  '¿Qué es lo más hermoso de eso?',
  '¿Con qué evento histórico se asocia más?',
  '¿Con qué emoción o sentimiento se asocia más?',
  '¿Qué número se asocia más con ello? (Escríbelo)',
  '¿Con qué se empareja bien?',
  '¿Con qué flor se asocia más?',
  '¿Cuál es una forma alternativa de usarlo?',
  'Si entrecierras los ojos, ¿cómo se ve?',
  '¿Cuál es un color que no tiene?',
  '¿Cuál es un componente de ello?',
  '¿Con qué era de la historia se asocia más?',
  '¿Qué tipo de pantalones usaría?',
  '¿Cómo puede ser aterrador?',
  '¿Cómo lo usaría un niño?',
  'Si tuviera personalidad, ¿qué tipo de personalidad tendría?',
  '¿Qué sería como mascota?',
  '¿En qué tipo de arte podría aparecer?',
  '¿En qué circunstancias es inútil?',
  'Si fuera una gema, ¿qué gema sería?',
  '¿A qué se parece en forma?',
  '¿Con qué hobby se asocia más?',
  'Si se usara en un deporte olímpico, ¿cuál sería?',
  '¿Qué anunciaría en la TV?',
  'Si fuera un insecto, ¿qué insecto sería?',
  '¿Qué tipo de patrones tendría?',
  '¿Qué animal haría el mejor uso de ello?',
  '¿Con qué vehículo se asocia más?',
  '¿Qué unidades usarías para medirlo?',
  '¿Quién o qué lo toca?',
  'Si fuera un pájaro, ¿qué tipo de pájaro sería?',
  '¿En qué tipo de museo podrías encontrarlo?',
  '¿Qué lo mantiene unido?',
  '¿Cómo afecta a tu salud?',
  'Si tuviera un trabajo, ¿cuál sería?',
  'Si fuera un dulce, ¿qué dulce sería?',
  '¿Cuál es su mayor miedo?',
  '¿Qué verbo usas con él?',
  '¿Qué canción se relaciona con él o aparece en él?',
  '¿Qué pasaría si cada uno de estos objetos desapareciera?',
  '¿Con qué elemento clásico se asocia más? (Fuego, agua, etc.)',
  '¿Qué parte de él está oculta?',
  '¿Con qué villano se asocia más?',
  '¿Cómo lo usarían tus padres?',
  '¿Cómo se relaja?',
  '¿Qué es cuando es joven?',
  '¿Qué le pasa cuando envejece?',
  '¿A qué fruta, vegetal o planta se parece más?',
  'Si fuera un utensilio de cocina, ¿cuál sería?',
  '¿Qué pasaría si lo calentaras?',
  '¿Qué objeto usarías para medirlo?',
  '¿Cuál es su enemigo mortal?',
  '¿Con qué elemento de la tabla periódica se asocia más?',
  '¿Qué es lo peor de él?',
  'Si tuviera un nombre humano, ¿cuál sería?',
  '¿Qué haría un mago con él?',
  '¿En qué parte de la biblioteca encontrarías información sobre él?',
  '¿Con qué carta del tarot se asocia más?',
  'Si fuera un edificio, ¿qué estilo arquitectónico tendría?',
  '¿En qué tipo de revista aparecería?',
  '¿Con qué tipo de clima se asocia más?',
];